name: Test login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [Linux, x64, Self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install node
        run: npm install
      
      - name: Run Selenium tests and generate report
        run: npx mocha login.spec.js --reporter mochawesome --reporter-options reportDir=csc-360-project,reportFilename=index,quiet=true
      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: csc-360-project
          path: csc-360-project
